apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cic1
  # namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cic1
    name: in-cluster
  project: cic-apps
  source:
    path: cic/charts/citrix-ingress-controller-1
    repoURL: 'https://github.com/priyankash-citrix/helm.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
